### ISSUE TITLE
Wraptor debugging conflicts

### ISSUE THREAD

**Issue by jjmontesl** [carlsverre/wraptor#1]
When debugging from PyDev, I get the following warning:

> PYDEV DEBUGGER WARNING:
> sys.settrace() should not be used when the debugger is being used.
> This may cause the debugger to stop working correctly.
> If this is needed, please check: 
> http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
> to see how to restore the debug tracing back correctly.
> Call Location:
>   File "/env/local/lib/python2.7/site-packages/wraptor/context/maybe.py", line 25, in __exit__
>     sys.settrace(None)

We can see that the `maybe.py` module is indeed using tracing facilities:

```
    def __enter__(self):
        if not self.predicate():
            sys.settrace(self.__empty_fn)
            frame = inspect.currentframe(1)
            frame.f_trace = self.__trace

    def __trace(self, *args, **kwargs):
        raise _SkippedBlock()

    def __exit__(self, type, value, traceback):
        if isinstance(value, _SkippedBlock):
            sys.settrace(None)
            return True
        return False
```

What do you think? What is the motivation for using settrace? Any suggestion about how to remove calls to settrace?

**Comment by carlsverre** [comment]
The maybe decorator was a bit of an experiment with how far you could take context in Python.  You should be using an `if` statement instead.  So instead of:
```
with maybe(lambda: i == 3):
  print("hi")
```
do
```
if i == 3:
  print("hi")
```
